export const PAGENAME = {
  HOME: "HomePage",
  LOGIN: "LoginPopup",
  LOGGEDINHOME: "LoggedInHomePage",
  SHOPBYCATEGORY: "ShopByCategory",
  SNACKS: "ViewAllSnacks",
  PRODUCTDETAIL: "ProductDetail",
  SMARTLABELNUTRITIONANDINGREDIENTS: "Smartlabel-NutritionAndIngredients",
  CART: "CartReview",
  CHECKOUT: "Checkout",
  GUESTCHECKOUT: "GuestCheckout",
  PAYMENT: "Payment",
  THANKYOU: "ThankYou",
  VARIETY: "VarietyPack",
  VARIETYDETAIL: "VarietyPackDetail",
  HOLIDAY: "HolidayShop",
  HOLIDAYDETAIL: "HolidayShopDetail",
  MYPROFILE: "MyProfile",
  ORDERHISTORY: "OrderHistory",
  CHANGEPASSWORD: "ChangePassword",
  SHIPPINGRETURN: "Shipping&ReturnPolicy",
  TERMSERVICE: "TermsOfService",
  CONTACTUS: "ContactUs",
  PRIVACYPOLICY: "PrivacyPolicy",
  ADSTRACKING: "Ads&Tracking",
  CREATEACCOUNT: "CreateAccount",
  PAGENOTFOUND: "PageNotFound",
  SOMETHINGWENTWRONG: "SomethingWentWrongPage",
  TANGYPICKLE: "TangyPickle",
  TWISTEDLIME: "TwistedLime",
  NUTRITIONFACTS: "Smartlabel-Nutrition",
  INGREDIENTINFO: "Smartlabel-Ingredients",
  CALLOFDUTYRULES: "CallOfDutyRules",
};

export const SELECTEDEVENTNAME = {
  NAVIGATION: "NavigationLink",
  HOMELINK: "HomeLink",
  SHOPCATEGORY: "ShopCategory",
  SHOPSUBCATEGORY: "ShopSubCategory",
  FOOTERLINK: "FooterLink",
  DAYSFILTER: "DaysFilter",
  HOLIDAYSIZEDROPDOWN: "HolidaySizeDropdown",
  FINALSELECTEDCAT: "FinalSelectedCategoryList",
};

export const BUTTONNAME = {
  LOGIN: "LoginBtn",
  SUBMIT: "SubmitBtn",
  SIGNIN: "SigninBtn",
  LOGOUT: "LogoutBtn",
  FORGOTPASSWORD: "ForgotPasswordBtn",
  BACKTOSIGNIN: "BackToSignInBtn",

  EDITMULTIPACK: "EditVarietyPack",
  SHOWMULTIPACKDETAIL: "ShowVarietyPackDetail",
  SHOWTANGYPICKLEDETAIL: "ShowTangyPickleItemDetail",
  SEEALL: "SeeAllBtn",

  ADDTOCART: "AddToCartBtn",
  ORDERMIX: "OrderThisMixBtn",
  UPDATECART: "UpdateCartBtn",
  DELETEPRODUCT: "DeleteProductBtn",

  SHIPTO: "ShipToBtn",
  ZIPCODEUPDATE: "ZipCodeUpdatedBtn",
  ZIPCODEUPDATECANCEL: "ZipCodeUpdateCancelBtn",

  CHECKOUT: "CheckoutBtn",
  CART: "CartBtn",
  CREATEACCOUNT: "CreateAccountBtn",
  CONTINUEASGUEST: "ContinueAsGuestBtn",
  CONTINUESHOPPING: "ContinueShoppingBtn",
  CONTINUETOPAYMENT: "ContinueToPaymentBtn",

  APPLYFILTERS: "ApplyFilters",
  CLEARALLFILTERS: "ClearAllFilters",
  CLEARALLCART: "ClearAllCart",
  YES: "YesBtn",
  CANCEL: "CancelBtn",
  ORDERHISTORYDETAIL: "OrderHistoryDetail",
  HOLIDAYDETAILPOPUP: "HolidayProductDetailPopup",
  PRODUCTDETAILPOPUP: "ProductDetailPopup",
  SIZECHART: "SizeChartBtn",
  REORDER: "ReOrderBtn",
  SUBMITORDER: "SubmitOrderBtn",

  NEXT: "NextBtn",
  BACK: "BackBtn",
  CHANGE: "ChangeBtn",
  REMOVE: "RemoveBtn",
  APPLY: "ApplyBtn",

  ADDNEWADDRESS: "AddNewAddress",
  CANCELADDADDRESS: "CancelAddNewAddress",

  CREATESHIPPINGADD: "CreateShippingAddress",
  SAVESHIPPINGADD: "SaveShippingAddress",
  EDITSHIPPINGADD: "EditShippingAddress",
  CANCELSHIPPINGADD: "CancelShippingAddress",
  DELETESHIPPINGADD: "DeleteShippingAddress",
  UPDATESHIPPINGADD: "UpdateShippingAddress",
  ADDNEWSHIPPINGADD: "AddNewShippingAddress",
  PRIMARYSHIPPINGADD: "PrimaryShippingAddress",
  SAMEASSHIPPINGADD: "SameAsShippingAddress",

  CREATEBILLINGADD: "CreateBillingAddress",
  UPDATEBILLINGADD: "UpdateBillingAddress",
  EDITBILLINGADD: "EditBillingAddress",
  SAVEBILLINGADD: "SaveBillingAddress",
  CANCELBILLINGADD: "CancelBillingAddress",

  SAVECHANGEDPASSWORD: "SaveChangedPassword",

  UPDATECONTACTINFO: "UpdateContactInfo",
  SAVECONTACTINFO: "SaveContactInfo",
  CANCELCONTACTINFO: "CancelContactInfo",
  EDITCONTACTINFO: "EditContactInfo",
  RELOAD: "ReloadBtn",
  CONTACTUS: "ContactUsBtn",

  BACKTOALLPRODUCTS: "BackToAllProducts",
  NOTIFYME: "NotifyMe",
  PRODUCTLIST: "ProductList",

  PRODUCTDETAIL: "ProductDetail",
  NUTRITIONANDINGREDIENTINFO: "NutritionFactsAndIngredientsInfo",
  NUTRITIONFACTSINFO: "Nutrition Facts",
  INGREDIENTSINFO: "IngredientsInfo",
  PRODUCTTILELABEL: "CODRulesLink",

  GIFTORDER: "GiftOrderCheckbox",
  INCLUDEECARD: "IncludeECardCheckbox",
  EDITGIFTECARD: "EditGiftECard",
  SELECTGIFTECARD: "SelectECard",
  GIFTINGMODALCLOSED: "GiftingModalClosed",
  CUSTOMIZEDGIFTCARD: "FinishGiftCardCustomization",
  DIFFERENTBILLINGADDRESS: "DifferentBillingAddress",
  SAMEBILLINGADDRESS: "SameBillingAddress",

  SAVEMIXANDNAMEVP: "SaveAndNameVarietyPack",

  FLAMINHOTNAVIGATIONMENUOPTION: "FlaminHotNavigationMenuOption",
  MYOVPNAVIGATIONMENUOPTION: "MYOVPNavigationMenuOption",
};

export const METHOD = {
  PRODUCTTILE: "ProductTile",
  PRODUCTTILELABEL: "CODRules",
  ORDERHISTORY: "OrderHistory",
  HOLIDAYTILE: "HolidayShopProductTile",
  POPULARTILE: "PopularTile",
  VARIETY: "VarietyPackTile",
  SHIPPING: "SHIPPING",
  COUPON: "Coupon",
  HEADER: "Header",
  FOOTER: "Footer",
  MINICART: "MiniCart",
  HOMEBOTTOM: "HomeBottom",
  DELETEDIALOGBOX: "DeleteDialogBox",
  UNSELECTED: "UnSelected",
  SELECTED: "Selected",
  TANGYPICKLE: "TangyPicklePage",
  TWISTEDLIME: "TwistedLimePage",
  GIFTORDERCHECKED: "GiftOrderChecked",
  GIFTORDERUNCHECKED: "GiftOrderUnchecked",
  INCLUDEGIFTINGECARD: "IncludeGiftingECard",
  EXCLUDEGIFTINGECARD: "ExcludeGiftingECard",
  EDITGIFTINGECARD: "EditGiftingECard",
  SELECTECARDTOCUSTOMIZED: "SelectECardToCustomized",
  GIFTINGMODAL: "GiftingModal",
  GIFTCARDCUSTOMIZED: "GiftCardCustomization",
  CHANGEDGIFTINGBILLINGADDRESSOPTION: "ChangedGiftingBillingAddressOption",
  FLAMINHOTNAVIGATIONMENU: "FlaminHotNavigationMenuOption",
  MYOVPNAVIGATIONMENU: "MYOVPNavigationMenuOption",
};

export const PRODUCTTYPE = {
  VARIETY: "VarietyPack",
  HOLIDAY: "HolidayShop",
  SNACKS: "Snacks",
};

export const FOOTERLINKS = {
  LOGO: "SnacksCom",
  FRITOLAY: "Fritolay",
  TWITTER: "Twitter",
  FACEBOOK: "Facebook",
  INSTAGRAM: "Instagram",
  SHIPPINGRETURN: "Shipping&ReturnPolicy",
  WEBSITEACCESSIBILITY: "WebsiteAccessibilityStatement",
  TERMSERVICE: "TermsOfService",
  CONTACTUS: "ContactUs",
  PRIVACYPOLICY: "PrivacyPolicy",
  ADSTRACKING: "Ads&Tracking",
  TASTYREWARDS: "TastyRewards",
};

/* Tasty Rewards */
export const FOOTERLINKS_TR = {
  LOGO: "TastyRewardsCom",
  ABOUTUS: "AboutUs",
  CONTACTUS: "ContactUs",
  FAQ: "FAQ",
  SNACKCOM: "SnacksCom",
  PRIVACYPOLICY: "PrivacyPolicy",
  TERMUSE: "TermsOfUse",
  ABOUTADS: "AboutOurAds",
  UNSUBSCRIBE: "Unsubscribe",
  CHANGECOUNTRY: "ChangeCountry",
  TASTYREWARDS: "TastyRewards",
};
