//This file will have content constant and reg ex constants

export const DisplayHeading = {
  SITE_NAME: "Snacks.com",
  TASTY_REWARDS_SITE_NAME: "TastyRewards.com",
  TASTY_REWARDS: "Tasty Rewards",
  OUT_OF_STOCK: "OUT OF STOCK",
  NOT_AVAILABLE: "NOT AVAILABLE",
  CHECK_IT_OUT: "CHECK IT OUT",
  GET_STARTED: "GET STARTED",
  SEE_ALL: "SEE ALL",
  SELECT: "select",
  SELECTED: "Added to Cart",
  EDIT: "EDIT",
  LOG_IN: "Log In",
  SIGN_IN: "Sign in",
  TASTY_REWARDS_SIGN_IN: "Sign In & Get Started",
  FORGOT_PASSWORD: "Forgot password",
  SHIPPING_INFORMATION: "SHIPPING INFORMATION",
  SHIPPING_ADDRESS: "SHIPPING ADDRESS",
  EDIT_SHIPPING_ADDRESS: "EDIT SHIPPING ADDRESS",
  ADD_ANOTHER_SHIPPING_ADDRESS: "ADD ANOTHER SHIPPING ADDRESS",
  CONTACT_INFORMATION: "CONTACT INFORMATION",
  BILLING_INFORMATION: "BILLING INFORMATION",
  BILLING_ADDRESS: "BILLING ADDRESS",
  EDIT_BILLING_ADDRESS: "EDIT BILLING ADDRESS",
  CONTINUE_SHOPPING: "CONTINUE SHOPPING",
  YOUR_ORDER: "YOUR ORDER",
  CLEAR_CART: "CLEAR CART",
  CONTINUE: "CONTINUE",
  CHECKOUT: "CHECKOUT",
  GUEST_CHECKOUT: "GUEST CHECKOUT",
  CREATE_ACCOUNT: "CREATE ACCOUNT",
  ORDER_SUMMARY: "ORDER SUMMARY",
  CANCEL: "CANCEL",
  SAVE: "SAVE",
  NEXT: "Next",
  BACK: "Back",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  DONE: "DONE",
  TR_FORGOT_PASSWORD_TITLE: "Having Trouble Sigining In?",
  SUBMIT_ORDER: "SUBMIT ORDER",
  PRODUCT_LIST_TITLE: "View All Snacks",
  HOLIDAY_SHOP: "Holiday Shop",
  YOUR_EMPTY_CART: "Your cart is empty",
  SHOP_BY_CATEGORY_TITLE: "Shop By Category",
  SHOP_BY_CATEGORY_SUB_TITLE: "Select from the 4 categories.",
  SHOP_BY_CATEGORY_SNACKING: "LET'S GET SNACKING",
  SHOP_BY_CATEGORY_SELECT_ITEM: "Select the items that you are interested in.",
  REVIEW_YOUR_CART: "review your cart",
  DESCRIPTION: "description",
  NUTRITION_FACTS: "Nutrition Facts",
  INGREDIENTS: "Ingredients",
  NUTRITION_FACTS_AND_INGREDIENT_INFO: "Nutrition Facts & Ingredients Info",
  ALL_CART_FAVORITES: "All your favorites are here!",
  CART_FREE_SHIPPING: "Plus free shipping on orders over $",
  COVID_WARNING: `Note: We are currently experiencing shipping delays due to COVID-19.
    All orders are processed in the order that they are received,
    and we are doing our best to ship all orders on time.
    Thank you for your patience.`,
  MP_DISCLAIMER: `Due to high demand, the box you receive may differ from previous orders.`,
  ALL_SALES_NOTE: "All sales are final.",
  THANK_YOU: "THANK YOU##NAME##",
  CONTINUE_TO_PAYMENT: "CONTINUE TO PAYMENT",
  NOT_AVAILABLE_FLAG_MSG: `This product is not available for
    selected shipping zip code.`,
  FREE_SHIPPING_MSG: "Minimum order of",
  MULTIPACK_PRODUCT: `We’re sorry, but one or more of your selected items are no longer available.
   Click "Edit button" and replace with a new item.`,
  VIEW_ORDER: "VIEW & ORDER",
  MP_LOGIN_MSG: `Log into your Snacks.com account to save your mixes here for easy re-ordering.`,
  CREATE_AN_ACCOUNT: "CREATE AN ACCOUNT",
  CONTACT_US_PAGE: "CUSTOMER SUPPORT",
  PAYMENT_PAGE: "Payment",
  CONTACT_US_BUTTON: "Contact Us",
  PRIVACY_POLICY_BUTTON: "Privacy Policy",
  TERMS_OF_SERVICE_BUTTON: "Terms of Service",
  ADS_TRACKING_BUTTON: "About Our Ads",
  WEBSITE_ACCESSIBILITY: "Website Accessibility Statement",
  COMMON_QUESTIONS: "COMMON QUESTIONS",
  CONTACT_US_HEADER: "Contact Customer Service",
  NOTIFY_ME: "Notify Me",
  CREATE_MIX: "Create Mix",
  NO_SAVED_MIX: "No Saved Mixes yet!",
  ABOUT_US: "About Us",
  FAQ: "FAQ",
  TERMS_OF_USE: "Terms of Use",
  ABOUT_OUR_ADS: "About Our Ads",
  Unsubscribe: "Unsubscribe",
  BUNDLE_PRODUCT: `We’re sorry, but one or more of your selected items are no longer available.`,
  SHIPPING_AND_DELIVERY: "Shipping & Returns",
  RETURNS: "Returns",
};

export const MessagesUtil = {
  EMAIL_REQUIRED: "Email is required.",
  RECIPIENT_EMAIL_REQUIRED: "Recipient's email is required.",
  EMAIL_NOT_VALID: "Email address should be in XXXX@address.com format.",
  CONTACT_REQUIRED: "Phone Number is required.",
  CONTACT_NOT_VALID: "Phone Number must be a number type.",
  CONTACT_MIN_MAX_LIMIT: "Phone Number must be 10 digits.",
  FIRST_NAME_REQUIRED: "First Name is required.",
  LAST_NAME_REQUIRED: "Last Name is required.",
  NAME_MIN_LIMIT: "Name must be at least 2 characters.",
  NAME_MAX_LIMIT: "Name cannot be longer than 30 characters.",
  NAME_ONLY_ALPHABETS: "Name must be only alphabets.",
  FIRST_NAME_NOT_VALID: "First Name must be only alphabets",
  LAST_NAME_NOT_VALID: "Last Name must be only alphabets",
  ADDRESS_REQUIRED: "Address is required.",
  PO_BOX_NOT_VALID:
    "Cannot ship to P.O. Box. Please provide another ##ADDTYPE## address.",
  CITY_REQUIRED: "City is required.",
  STATE_REQUIRED: "State is required.",
  ZIP_CODE_REQUIRED: "Zip is required",
  ZIP_CODE_NOT_VALID: "Zip code must be exactly 5 digits.",
  ADDRESS1_REQUIRED: "Address Line is required.",
  COUNTRY_REQUIRED: "Country is required",
  SPECIAL_CHARS_NOT_VALID: "Special characters are not allowed",
  SUBJECT_REQUIRED: "Subject is required",
  NAME_REQUIRED: "Name is required",
  DESCRIPTION_REQUIRED: "Description is required",
  ADDRESSLINE1_NOT_VALID: "Address Line 1 must be only alphabets.",
  ADDRESSLINE2_NOT_VALID: "Address Line 2 must be only alphabets.",
  ADDRESSLINE_MAX_LIMIT: "Address cannot be longer than 30 characters.",
  CITY_NOT_VALID: "City must be only alphabets.",
  PASSWORD_REQUIRED: "Pasword is required.",
  PASSWORD_MIN_LIMIT: "Password must be at least 8 characters.",
  PASSWORD_NOT_VALID: "Please enter a valid password.",
  HELP_ME_VERIFY_TEXT: "Help me verify",
  API_FAIL_RELOAD_PAGE: "Reload",
  DAY_NOT_VALID: "Day is required",
  MONTH_NOT_VALID: "Month is required",
  YEAR_NOT_VALID: "Year is required",
  GENDER_NOT_VALID: "Gender is required",
  TERMS_CHECKBOX_REQUIRED: "Terms & Conditions is required",
  AGE_NOT_VALID: "Sorry! You must be 18 or older to register for the concert.",
};

export const RegexUtil = {
  ADDRESS_PO_BOX: /\bP(ost|ostal)?([ \.]*(O|0)(ffice)?)?([ \.]*Box)\b/i,
  ADDRESS_ALPHA: /^[a-zA-Z0-9 '.#,/'-]*$/,
  CONTACT_NO: /((\([0-9]{3}\))|[0-9]{3})[\s-]?[\0-9]{3}[\s-]?[0-9]{4}$/,
  NAME: /^[a-zA-Z.&' ]*$/,
  ZIP_CODE: /^[0-9]{5}$/,
  ZIP_CODE_OR_NUM: /^[0-9\b]+$/,
  EMAIL:
    /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
  WITHOUT_SPECIAL_CHARS: /[^\w\s]/gi,

  // Minimum eight characters, at least one uppercase letter, one lowercase letter and one number
  PASSWORD:
    /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!#$%&â€™()*+,-./\:;<=>?@\[\]^_`{|}~])[a-zA-Z\d!#$%&â€™()*+,-./\:;<=>?@\[\]^_`{|}~]{8,}$/,
};

export const dayArray = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "20",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
  "27",
  "28",
  "29",
  "30",
  "31",
];
export const monthArray = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
export const yearArray = [
  "2008",
  "2007",
  "2006",
  "2005",
  "2004",
  "2003",
  "2002",
  "2001",
  "2000",
  "1999",
  "1998",
  "1997",
  "1996",
  "1995",
  "1994",
  "1993",
  "1992",
  "1991",
  "1990",
  "1989",
  "1988",
  "1987",
  "1986",
  "1985",
  "1984",
  "1983",
  "1982",
  "1981",
  "1980",
  "1979",
  "1978",
  "1977",
  "1976",
  "1975",
  "1974",
  "1973",
  "1972",
  "1971",
  "1970",
  "1969",
  "1968",
  "1967",
  "1966",
  "1965",
  "1964",
  "1963",
  "1962",
  "1961",
  "1960",
  "1959",
  "1958",
  "1957",
  "1956",
  "1955",
  "1954",
  "1953",
  "1952",
  "1951",
  "1950",
  "1949",
  "1948",
  "1947",
  "1946",
  "1945",
  "1944",
  "1943",
  "1942",
  "1941",
  "1940",
  "1939",
  "1938",
  "1937",
  "1936",
  "1935",
  "1934",
  "1933",
  "1932",
  "1931",
  "1930",
  "1929",
  "1928",
  "1927",
  "1926",
  "1925",
  "1924",
  "1923",
  "1922",
  "1921",
  "1920",
  "1919",
  "1918",
  "1917",
  "1916",
  "1915",
  "1914",
  "1913",
  "1912",
  "1911",
  "1910",
  "1909",
];

export const NAVIGATION_COUNT_MANAGE = {
  brandsListMaxCount: 12,
  parentCatMaxCount: 4,
  subCategoryMaxCount: 10,
  promotionTileMaxCount: 2,
};

export const BANNER_CONFIG_LIST = [
  {
    bannerTitle: "All Snacks",
    bannerTxtColor: "",
    bannerBgColor: "#0BB9FA",
    pills: false,
    imageTile: true,
    description:
      "Crunch, crunch, crunch away with a wide variety of chip options. Have it hot, zesty, or cheesy –– flavor is calling and we think you should answer.",
  },
  {
    bannerTitle: "Chips",
    bannerTxtColor: "",
    bannerBgColor: "",
    pills: true,
    imageTile: false,
    description:
      "Crunch, crunch, crunch away with a wide variety of chip options. Have it hot, zesty, or cheesy –– flavor is calling and we think you should answer.",
  },
  {
    bannerTitle: "All Brands",
    bannerTxtColor: "#fff",
    bannerBgColor: "#51127F",
    pills: false,
    imageTile: false,
    description:
      "Crunch, crunch, crunch away with a wide variety of chip options. Have it hot, zesty, or cheesy –– flavor is calling and we think you should answer.",
  },
];

export const SnacksCategoryIds = {
  snackType: "Snack Type",
  brand: "Brand",
  flavor: "Flavor",
};
